# Generated by Django 6.0.7 on 2026-07-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(db_index=True, help_text='Phone number for the contact.', max_length=20)),
                ('company_name', models.CharField(blank=True, default='', help_text='Prospect company name as text.', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, help_text='The salesperson assigned to this contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_salesperson', 'is_active', 'is_deleted'], name='contacts_co_assigne_f9c295_idx')],
            },
        ),
    ]
