# Generated by Django 6.0.7 on 2026-07-22 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_assigne_f9c295_idx',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Job title or designation.', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, default='', help_text='Primary phone number.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='assigned_salesperson',
            field=models.ForeignKey(blank=True, help_text='Salesperson assigned to manage this contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Prospect company name.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_salesperson', 'status', 'is_deleted'], name='contacts_co_assigne_6c1507_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone_number', 'email', 'is_deleted'], name='contacts_co_phone_n_55956d_idx'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
