# Generated by Django 6.0.7 on 2026-07-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, help_text='Phone number for the lead.', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('company_name', models.CharField(help_text='Prospect company name as text.', max_length=255)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('FACEBOOK', 'Facebook'), ('GOOGLE_ADS', 'Google Ads'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk-in'), ('PHONE_CALL', 'Phone Call'), ('EMAIL_CAMPAIGN', 'Email Campaign'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('PROPOSAL_SENT', 'Proposal Sent'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('contact_attempts', models.PositiveIntegerField(default=0)),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('lost_reason', models.CharField(blank=True, choices=[('BUDGET_TOO_HIGH', 'Budget Too High'), ('NOT_INTERESTED', 'Not Interested'), ('COMPETITOR_CHOSEN', 'Competitor Chosen'), ('NO_RESPONSE', 'No Response'), ('WRONG_CONTACT', 'Wrong Contact'), ('PROJECT_POSTPONED', 'Project Postponed'), ('DUPLICATE_LEAD', 'Duplicate Lead'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('lost_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, help_text='The salesperson assigned to this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_salesperson', 'status', 'is_converted'], name='leads_lead_assigne_077b48_idx')],
            },
        ),
    ]
