# Generated by Django 6.0.7 on 2026-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Phone number for the lead.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('PROPOSAL_SENT', 'Proposal Sent'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=30),
        ),
    ]
