# Generated by Django 6.0.7 on 2026-07-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_migrate_legacy_companies'),
        ('contacts', '0004_alter_contact_company_remove_contact_company_name'),
        ('leads', '0002_lead_converted_at_alter_lead_phone_alter_lead_status'),
        ('opportunities', '0003_alter_opportunity_company_remove_opportunity_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='companies.company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='opportunities.opportunity'),
        ),
    ]
