# Generated by Django 6.0.7 on 2026-07-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_pipeline_stage'),
        ('pipeline', '0003_pipeline_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='pipeline.pipeline'),
        ),
    ]
