# Generated by Django 6.0.7 on 2026-07-27 18:55

from django.db import migrations


def populate_pipeline_fk(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    Opportunity = apps.get_model('opportunities', 'Opportunity')
    Pipeline = apps.get_model('pipeline', 'Pipeline')
    
    default_pipeline = Pipeline.objects.filter(is_default=True).first()
    if not default_pipeline:
        default_pipeline = Pipeline.objects.first()
    if not default_pipeline:
        default_pipeline = Pipeline.objects.create(name="Default Pipeline", is_default=True)

    for lead in Lead.objects.all():
        if lead.pipeline_stage:
            lead.pipeline_id = lead.pipeline_stage.pipeline_id
        else:
            lead.pipeline = default_pipeline
        lead.save()

    for opp in Opportunity.objects.all():
        if opp.pipeline_stage:
            opp.pipeline_id = opp.pipeline_stage.pipeline_id
        else:
            opp.pipeline = default_pipeline
        opp.save()

def rollback_pipeline_fk(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_pipeline'),
        ('opportunities', '0005_opportunity_pipeline'),
        ('pipeline', '0003_pipeline_is_default'),
    ]

    operations = [
        migrations.RunPython(populate_pipeline_fk, rollback_pipeline_fk),
    ]
