# Generated by Django 6.0.7 on 2026-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='employee_count',
            field=models.IntegerField(blank=True, help_text='Number of employees.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, default='OTHER', help_text='Industry of the company.', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Company website URL.'),
        ),
    ]
