# Generated by Django 6.0.7 on 2026-09-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Unique gateway event identifier (e.g. evt_...)', max_length=255, unique=True)),
                ('gateway', models.CharField(default='STRIPE', help_text='Gateway provider name', max_length=50)),
                ('event_type', models.CharField(db_index=True, help_text='Type of event (e.g. payment_intent.succeeded)', max_length=100)),
                ('payload', models.JSONField(help_text='Full verified gateway event JSON payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Processing status of webhook event', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error detail if processing failed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when event was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Webhook Inbox',
                'verbose_name_plural': 'Webhook Inboxes',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
