# Generated by Django 6.0.7 on 2026-09-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_webhookinbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='dunninglog',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID (pi_...) associated with retry', max_length=255),
        ),
        migrations.AddField(
            model_name='dunninglog',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Deterministic unique key preventing duplicate retry execution', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dunninglog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled'), ('EXHAUSTED', 'Exhausted')], help_text='Result of retry attempt', max_length=20),
        ),
    ]
