# Generated by Django 6.0.7 on 2026-07-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('LEAD', 'Lead'), ('OPPORTUNITY', 'Opportunity')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('stage_type', models.CharField(choices=[('NORMAL_LEAD', 'Normal Lead'), ('CONVERSION', 'Conversion Stage'), ('NORMAL_OPPORTUNITY', 'Normal Opportunity'), ('WON', 'Won Stage'), ('LOST', 'Lost Stage')], default='NORMAL_LEAD', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipeline.pipeline')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('pipeline', 'order'), name='unique_stage_order_per_pipeline')],
            },
        ),
    ]
