# Generated by Django 6.0.7 on 2026-07-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_setup_standard_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
