# Generated by Django 6.0.7 on 2026-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_pipelinestage_is_deleted_customform_customformfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinestage',
            name='entity_type',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('OPPORTUNITY', 'Opportunity')], default='LEAD', max_length=20),
        ),
    ]
