# Generated by Django 6.0.7 on 2026-08-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='catalog.pricingplan'),
        ),
    ]
