# Generated by Django 6.0.7 on 2026-07-23 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner'), ('COMPETITOR', 'Competitor'), ('OTHER', 'Other')], db_index=True, default='PROSPECT', max_length=50)),
                ('rating', models.CharField(choices=[('NONE', 'None'), ('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], db_index=True, default='NONE', max_length=50)),
                ('industry', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('billing_address', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_address', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, help_text='Salesperson assigned to manage this company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
