# Generated by Django 6.0.7 on 2026-07-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_migrate_legacy_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, db_index=True, default=''),
        ),
    ]
