# Generated by Django 6.0.7 on 2026-07-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_remove_contact_contacts_co_assigne_f9c295_idx_and_more'),
        ('leads', '0002_lead_converted_at_alter_lead_phone_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(choices=[('QUALIFICATION', 'Qualification'), ('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], db_index=True, default='QUALIFICATION', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expected_close_date', models.DateField()),
                ('lead_source', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('lost_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, help_text='Salesperson assigned to manage this opportunity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='contacts.contact')),
                ('source_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_salesperson', 'stage'], name='opportuniti_assigne_6f0994_idx')],
            },
        ),
    ]
