# Generated by Django 6.0.7 on 2026-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_opportunity_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='custom_values',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
