# Generated by Django 6.0.7 on 2026-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunity_custom_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10),
        ),
    ]
