# Generated by Django 6.0.7 on 2026-08-05 05:22

import catalog.models.product
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of the module (e.g. Lead Management)', max_length=255)),
                ('code', models.SlugField(help_text='Code identifier for permission checks. Unique per product.')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this module offers')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this module is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this module is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the SaaS module/service (e.g. Sales CRM)', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing', unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', validators=[catalog.models.product.validate_product_image])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is active and visible')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this product is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the professional service (e.g. CRM Consultation)', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing', unique=True)),
                ('short_description', models.CharField(help_text='Brief summary of the service', max_length=500)),
                ('full_description', models.TextField(blank=True, help_text='Detailed description of the service')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', validators=[catalog.models.product.validate_product_image])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this service is active and visible')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this service is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Designates whether this module is active in the plan')),
                ('limit_value', models.CharField(blank=True, help_text="Custom module limit value if any (e.g. '500 leads', '5 users')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='catalog.module')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the pricing plan (e.g. Starter, Professional)', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the plan', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Three-letter currency code', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', help_text='Frequency of billing', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this plan is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this plan is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(help_text='Modules included in this pricing plan', related_name='plans', through='catalog.PlanModule', to='catalog.module')),
                ('product', models.ForeignKey(blank=True, help_text='The product this plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.product')),
                ('service', models.ForeignKey(blank=True, help_text='The service this plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.service')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='planmodule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='catalog.pricingplan'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the discount (e.g. Winter Sale)', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount (Percentage or Fixed Amount)', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage e.g. 20.00 or amount e.g. 50.00)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Manually enable/disable the discount')),
                ('start_date', models.DateTimeField(blank=True, help_text='Start date/time of the discount (optional)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='End date/time of the discount (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_plan', models.ForeignKey(help_text='The pricing plan this discount applies to', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='product',
            field=models.ForeignKey(help_text='The product this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name/description of the feature (e.g. Email Support)', max_length=255)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this feature is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='The service this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.service')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='planmodule',
            unique_together={('plan', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('product', 'code')},
        ),
    ]
