# Generated by Django 6.0.7 on 2026-07-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('APPROVE', 'Approve'), ('ASSIGN', 'Assign')], max_length=20)),
                ('scope', models.CharField(choices=[('ALL', 'All'), ('OWN', 'Own'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.crmresource')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'resource', 'action'), name='unique_role_permission')],
            },
        ),
    ]
